kmap = ["Checksum",
    "UNIX Time Stamp",
    "Mission ID",
    "Platform Tail Number",
    "Platform Heading Angle",
    "Platform Pitch Angle",
    "Platform Roll Angle",
    "Platform True Airspeed",
    "Platform Indicated Airspeed",
    "Platform Designation",
    "Image Source Sensor",
    "Image Coordinate System",
    "Sensor Latitude",
    "Sensor Longitude",
    "Sensor True Altitude",
    "Sensor Horizontal Field of View",
    "Sensor Vertical Field of View",
    "Sensor Relative Azimuth Angle",
    "Sensor Relative Elevation Angle",
    "Sensor Relative Roll Angle",
    "Slant Range",
    "Target Width",
    "Frame Center Latitude",
    "Frame Center Longitude",
    "Frame Center Elevation",
    "Offset Corner Latitude Point 1",
    "Offset Corner Longitude Point 1",
    "Offset Corner Latitude Point 2",
    "Offset Corner Longitude Point 2",
    "Offset Corner Latitude Point 3",
    "Offset Corner Longitude Point 3",
    "Offset Corner Latitude Point 4",
    "Offset Corner Longitude Point 4",
    "Icing Detected",
    "Wind Direction",
    "Wind Speed",
    "Static Pressure",
    "Density Altitude",
    "Outside Air Temperature",
    "Target Location Latitude",
    "Target Location Longitude",
    "Target Location Elevation",
    "Target Track Gate Width",
    "Target Track Gate Height",
    "Target Error Estimate - CE90",
    "Target Error Estimate - LE90",
    "Generic Flag Data 01",
    "Security Local Metadata Set",
    "Differential Pressure",
    "Platform Angle of Attack",
    "Platform Vertical Speed",
    "Platform Sideslip Angle",
    "Airfield Barometric Pressure",
    "Airfield Elevation",
    "Relative Humidity",
    "Platform Ground Speed",
    "Ground Range",
    "Platform Fuel Remaining",
    "Platform Call Sign",
    "Weapon Load",
    "Weapon Fired",
    "Laser PRF Code",
    "Sensor Field of View Name",
    "Platform Magnetic Heading",
    "UAS LDS Version Number",
    "Target Location Covariance Matrix",
    "Alternate Platform Latitude",
    "Alternate Platform Longitude",
    "Alternate Platform Altitude",
    "Alternate Platform Name",
    "Alternate Platform Heading",
    "Event Start Time - UTC",
    "Remote Video Terminal LDS Conversion"]

ak = ["","Command Control Interface","Data Link Interface & Command Control Interface"]
ak2 = ["","Co","D&C"]
avail = [
        1,
        2,
        1,1,
        2,2,2,
        1,1,1,
        2,
        1,
        2,2,2,2,2,2,2,
        1,1,1,1,1,1,1,1,1,1,1,1,1,1,
        2,
        1,1,
        2,2,2,
        1,1,1,1,1,1,1,1,1,
        2,2,2,2,
        1,1,1,
        2,
        1,
        2,
        1,1,1,1,1,
        2,2,
        1,
        2,2,2,2,2,
        1,1]
rk = ["","X"]
req = [
    1,1,1,
    0,
    1,1,1,
    0,0,
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,
    0,0,0,0,0,0,0,0
]
seckeys = [
        "Security Classification",
        "Classifying Country and Releasing Instructions Country Method",
        "Classifying Country",
        "SCI/SHI information",
        "Caveats",
        "Releasing Instructions",
        "Classified By",
        "Derived From",
        "Classification Reason",
        "Declassification Date",
        "Classification and Marking System",
        "Object Country Coding Method",
        "Object Country Codes",
        "Classification Comments",
        "UMID Video",
        "UMID Audio",
        "UMID Data",
        "UMID System",
        "Stream ID",
        "Transport Stream ID",
        "Item Designator ID",
        "Version"
]

def print_table():
    headers = ["required","DLI/CCI","UAS LDSKey","Name"]
    print(headers)
    for i in range(len(kmap)):
        print(rk[req[i]],ak2[avail[i]],i+1,kmap[i])
    
    print("")

def confirm():
    print(len(kmap),len(avail),len(req))

if __name__ == "__main__":
    #confirm()
    print_table()